## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugo-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

# Local
baseURL = "https://gudjao.github.io/wedding/"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "your-google-analytics-id"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]

[Params.social]

languageCode = 'en-US'
title = 'Wedding'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
disableKinds = ['RSS', 'taxonomy', 'term']
enableGitInfo = true